### ISSUE TITLE
error: java.io.FileNotFoundException: Too many open files

### ISSUE THREAD

**Issue by ghost** [baoxingsong/Irisas#4]
Hi :

When I try this command with default:
```
java -jar $p/Irisas.jar CutTheWholeGenomeWithWindow -r ref -l list -g ./need -o ./test
```
I meet this error:
>java.io.FileNotFoundException: ./test_2/Chr4/8020001_8030001 (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at java.io.FileWriter.<init>(FileWriter.java:78)
....
....
Exception in thread "pool-4-thread-11970" java.lang.NullPointerException
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
        at OtherFunctions.ReSdiWithWindowsedMsa.CutTheWholeGenomeWithaWindowRamSaveVersion$MyWriter.close(CutTheWholeGenomeWithaWindowRamSaveVersion.java:564)
        at OtherFunctions.ReSdiWithWindowsedMsa.CutTheWholeGenomeWithaWindowRamSaveVersion.runit2(CutTheWholeGenomeWithaWindowRamSaveVersion.java:337)
        at OtherFunctions.ReSdiWithWindowsedMsa.CutTheWholeGenomeWithaWindowRamSaveVersion.runit(CutTheWholeGenomeWithaWindowRamSaveVersion.java:233)
        at OtherFunctions.ReSdiWithWindowsedMsa.CutTheWholeGenomeWithaWindowRamSaveVersion.<init>(CutTheWholeGenomeWithaWindowRamSaveVersion.java:146)
        at Irisas.main(Irisas.java:52)
        ... 5 more

But when I try this command,It works.
```
 java -jar ${p}Irisas.jar CutTheWholeGenomeWithWindow -w 1000000 -v 100000 -r 10001 -l list -g ./need -o ./test
``` 
my system:
>ulimit -n
8192

I think for big genome, the methods to reduce the number of opening file is need.

**Comment by baoxingsong** [comment]
Thank you for pointing this out.
at line 149 of source code
src/OtherFunctions.ReSdiWithWindowsedMsa.CutTheWholeGenomeWithaWindowRamSaveVersion.java

You could change the value of ulimit. I hope it could works for your data and OS. I will update this in the future.
